name: isar_generator
description: Code generator for the Isar Database. Finds classes annotated with @IsarCollection.
version: 2.5.0
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.16.0 <3.0.0"

publish_to: none

dependencies:
  isar:
    git: 
      url: https://github.com/Giuspepe/isar-2.5.0
      path: packages/isar
  build: ^2.2.1
  source_gen: ^1.2.1
  analyzer: ">=4.0.0 <6.0.0"
  glob: ^2.0.2
  path: ^1.8.0
  dart_style: ^2.2.1
  dartx: ^1.0.0

dev_dependencies:
  lints: ^2.0.1
